ReceiptBudgeting: com.budget.receipt.service.OCRService Class Reference
com.budget.receipt.service.OCRService Class Reference
Public Member Functions
OCRService ()
Expense runOCR (String filePath, String budgetName)
Constructor & Destructor Documentation
OCRService()
com.budget.receipt.service.OCRService.OCRService ()
Member Function Documentation
runOCR()
Expense com.budget.receipt.service.OCRService.runOCR (String filePath, String budgetName)
runs OCR on the image at the specified file path
Parameters
filePath
References com.budget.receipt.model.expense.Expense.getCategory(), and com.budget.receipt.model.expense.Expense.getCost().
Referenced by com.budget.receipt.controller.BudgetController.scanComplete().
The documentation for this class was generated from the following file:
src/main/java/com/budget/receipt/service/OCRService.java