ReceiptBudgeting: com.budget.receipt.controller.BudgetController Class Reference
com.budget.receipt.controller.BudgetController Class Reference
Public Member Functions
BudgetController (ExpenseRepository expenseRepository, BudgetRepository budgetRepository)
String home (Model model)
String budgetDisplay (@PathVariable("id") long id, Model model)
String manualExpense (@PathVariable("id") long id, Model model)
String manualExpenseSumbit (@RequestParam("id") Long id, @ModelAttribute Expense expense, Model model)
String scan (@PathVariable("id") long id, Model model)
String scanComplete (@PathVariable("id") long id, Model model)
String submitExpense (@ModelAttribute Expense expense, Model model)
String newBudget (Model model)
String newBudgetSumbit (@ModelAttribute Budget budget, Model model)
Constructor & Destructor Documentation
BudgetController()
com.budget.receipt.controller.BudgetController.BudgetController (ExpenseRepository expenseRepository, BudgetRepository budgetRepository)
Member Function Documentation
budgetDisplay()
String com.budget.receipt.controller.BudgetController.budgetDisplay (@PathVariable("id") long id, Model model)
References com.budget.receipt.model.budget.Budget.getName(), and com.budget.receipt.service.ExpenseService.totalExpensesByBudget().
home()
String com.budget.receipt.controller.BudgetController.home (Model model)
manualExpense()
String com.budget.receipt.controller.BudgetController.manualExpense (@PathVariable("id") long id, Model model)
manualExpenseSumbit()
String com.budget.receipt.controller.BudgetController.manualExpenseSumbit (@RequestParam("id") Long id, @ModelAttribute Expense expense, Model model)
References com.budget.receipt.model.budget.Budget.getName().
newBudget()
String com.budget.receipt.controller.BudgetController.newBudget (Model model)
newBudgetSumbit()
String com.budget.receipt.controller.BudgetController.newBudgetSumbit (@ModelAttribute Budget budget, Model model)
scan()
String com.budget.receipt.controller.BudgetController.scan (@PathVariable("id") long id, Model model)
scanComplete()
String com.budget.receipt.controller.BudgetController.scanComplete (@PathVariable("id") long id, Model model)
References com.budget.receipt.model.expense.Expense.getCategory(), com.budget.receipt.model.expense.Expense.getCost(), com.budget.receipt.model.expense.Expense.getId(), com.budget.receipt.model.budget.Budget.getName(), and com.budget.receipt.service.OCRService.runOCR().
submitExpense()
String com.budget.receipt.controller.BudgetController.submitExpense (@ModelAttribute Expense expense, Model model)
The documentation for this class was generated from the following file:
src/main/java/com/budget/receipt/controller/BudgetController.java