ReceiptBudgeting: com.budget.receipt.model.expense.Expense Class Reference
com.budget.receipt.model.expense.Expense Class Reference
Public Member Functions
String getBudgetName ()
void setBudgetName (String budgetName)
Date getDate ()
void setDate (Date date)
long getId ()
BigDecimal getCost ()
void setCost (BigDecimal cost)
String getCategory ()
void setCategory (String category)
Detailed Description
A class representing an expense object.
Member Function Documentation
getBudgetName()
String com.budget.receipt.model.expense.Expense.getBudgetName ()
Getter for the budget name
Returns
the String name of the budget this expense belongs to.
getCategory()
String com.budget.receipt.model.expense.Expense.getCategory ()
Getter for the category name.
Returns
String category name.
Referenced by com.budget.receipt.service.OCRService.runOCR(), and com.budget.receipt.controller.BudgetController.scanComplete().
getCost()
BigDecimal com.budget.receipt.model.expense.Expense.getCost ()
Getter for the cost
Returns
a BigDecimal of the amount
Referenced by com.budget.receipt.service.OCRService.runOCR(), and com.budget.receipt.controller.BudgetController.scanComplete().
getDate()
Date com.budget.receipt.model.expense.Expense.getDate ()
Getter method for the date.
Returns
a Date object with the Date.
getId()
long com.budget.receipt.model.expense.Expense.getId ()
Getter for the expense ID
Returns
a Long ID
Referenced by com.budget.receipt.controller.BudgetController.scanComplete().
setBudgetName()
void com.budget.receipt.model.expense.Expense.setBudgetName (String budgetName)
Setter for the budget name
Parameters
budgetName String representing the budget name.
setCategory()
void com.budget.receipt.model.expense.Expense.setCategory (String category)
Setter for the category name.
Parameters
category a String category name.
setCost()
void com.budget.receipt.model.expense.Expense.setCost (BigDecimal cost)
Setter for the cost.
Parameters
cost the dollar amount of the expense.
setDate()
void com.budget.receipt.model.expense.Expense.setDate (Date date)
Setter for the date.
Parameters
date the date the expense occured.
The documentation for this class was generated from the following file:
src/main/java/com/budget/receipt/model/expense/Expense.java