ReceiptBudgeting: com.budget.receipt.model.budget.Budget Class Reference
com.budget.receipt.model.budget.Budget Class Reference
Public Member Functions
String getName ()
void setName (String name)
BigDecimal getIncome ()
void setIncome (BigDecimal income)
BigDecimal getAmountSpent ()
void setAmountSpent (BigDecimal amountSpent)
long getId ()
Detailed Description
This class refers to the basic budget list for the class. Category and Total Budgets extend this calass.
Member Function Documentation
getAmountSpent()
BigDecimal com.budget.receipt.model.budget.Budget.getAmountSpent ()
Returns the amount spent.
Returns
BigDecimal of the amount spent.
getId()
long com.budget.receipt.model.budget.Budget.getId ()
Returns the ID. Used only for testing.
Returns
long ID
getIncome()
BigDecimal com.budget.receipt.model.budget.Budget.getIncome ()
Getter for income
Returns
max amount of budget.
getName()
String com.budget.receipt.model.budget.Budget.getName ()
Getter for name of budget.
Returns
Name of the budget (string)
Referenced by com.budget.receipt.controller.BudgetController.budgetDisplay(), com.budget.receipt.controller.BudgetController.manualExpenseSumbit(), and com.budget.receipt.controller.BudgetController.scanComplete().
setAmountSpent()
void com.budget.receipt.model.budget.Budget.setAmountSpent (BigDecimal amountSpent)
Sets the amount spent on a budget.
Parameters
amountSpent BigDecimal reperesenting amount spent.
setIncome()
void com.budget.receipt.model.budget.Budget.setIncome (BigDecimal income)
Sets the income of the budget.
Parameters
income BigDecimal of max amount of budget.
setName()
void com.budget.receipt.model.budget.Budget.setName (String name)
Setter for name of budget
Parameters
name String name
The documentation for this class was generated from the following file:
src/main/java/com/budget/receipt/model/budget/Budget.java