ReceiptBudgeting: com.budget.receipt.web.SpringWebConfig Class Reference
com.budget.receipt.web.SpringWebConfig Class Reference
Public Member Functions
ITemplateResolver templateResolver ()
SpringTemplateEngine templateEngine ()
ThymeleafViewResolver viewResolver ()
ResourceBundleMessageSource messageSource ()
Detailed Description
Configures the web beans for Springboot.
Member Function Documentation
messageSource()
ResourceBundleMessageSource com.budget.receipt.web.SpringWebConfig.messageSource ()
Template for setting up Spring with Thymeleaf.
Returns
a template engine.
Referenced by com.budget.receipt.web.SpringWebConfig.templateEngine().
templateEngine()
SpringTemplateEngine com.budget.receipt.web.SpringWebConfig.templateEngine ()
Template for setting up Spring with Thymeleaf.
Returns
a template engine.
References com.budget.receipt.web.SpringWebConfig.messageSource(), and com.budget.receipt.web.SpringWebConfig.templateResolver().
Referenced by com.budget.receipt.web.SpringWebConfig.viewResolver().
templateResolver()
ITemplateResolver com.budget.receipt.web.SpringWebConfig.templateResolver ()
Serves to resolve templates so that pages will open properly.
Returns
a properly formatted html template
Referenced by com.budget.receipt.web.SpringWebConfig.templateEngine().
viewResolver()
ThymeleafViewResolver com.budget.receipt.web.SpringWebConfig.viewResolver ()
Template for setting up Spring with Thymeleaf.
Returns
a template engine.
References com.budget.receipt.web.SpringWebConfig.templateEngine().
The documentation for this class was generated from the following file:
src/main/java/com/budget/receipt/web/SpringWebConfig.java